# Generated by Django 6.1.1 on 2026-09-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RotationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(unique=True)),
                (
                    "area",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotation_slot",
                        to="chores.area",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
