# Generated by Django 6.1.1 on 2026-09-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0002_rotationslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_assignments",
                        to="chores.area",
                    ),
                ),
                (
                    "roommate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_assignments",
                        to="chores.roommate",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start", "roommate__order"],
            },
        ),
        migrations.CreateModel(
            name="TaskCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="chores.task",
                    ),
                ),
                (
                    "week_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completions",
                        to="chores.weekassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["task__order", "task__id"],
            },
        ),
        migrations.AddConstraint(
            model_name="weekassignment",
            constraint=models.UniqueConstraint(
                fields=("week_start", "roommate"), name="unique_roommate_per_week"
            ),
        ),
        migrations.AddConstraint(
            model_name="weekassignment",
            constraint=models.UniqueConstraint(
                fields=("week_start", "area"), name="unique_area_per_week"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskcompletion",
            constraint=models.UniqueConstraint(
                fields=("week_assignment", "task"),
                name="unique_task_per_week_assignment",
            ),
        ),
    ]
